"""Render a small KPI dashboard from the analytical database.

Reads database/supply_chain.db and produces a single PNG with the two
headline supply-chain views: late-delivery rate by shipping mode and
profitability by region. Output: reports/kpi_dashboard.png

Usage:
    python scripts/plot_kpis.py
"""

import sqlite3
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless rendering, no display needed
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config  # noqa: E402

REPORTS_DIR = config.BASE_DIR / "reports"

# Brand palette — calm, professional.
INK = "#1f2937"
ACCENT = "#2563eb"
GOOD = "#059669"
BAD = "#dc2626"
GRID = "#e5e7eb"


def load_frames(conn) -> tuple[pd.DataFrame, pd.DataFrame]:
    late_by_mode = pd.read_sql_query(
        """
        SELECT shipping_mode,
               ROUND(100.0 * AVG(is_late_delivery), 1) AS late_pct
        FROM fact_orders
        GROUP BY shipping_mode
        ORDER BY late_pct DESC
        """,
        conn,
    )
    profit_by_region = pd.read_sql_query(
        """
        SELECT order_region,
               ROUND(SUM(order_profit), 0) AS total_profit
        FROM fact_orders
        GROUP BY order_region
        ORDER BY total_profit DESC
        LIMIT 8
        """,
        conn,
    )
    # Plot top region at the top of the horizontal bar chart.
    profit_by_region = profit_by_region.iloc[::-1].reset_index(drop=True)
    return late_by_mode, profit_by_region


def render(late_by_mode: pd.DataFrame, profit_by_region: pd.DataFrame) -> Path:
    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "text.color": INK,
        "axes.edgecolor": GRID,
        "axes.labelcolor": INK,
        "xtick.color": INK,
        "ytick.color": INK,
    })

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5.2))
    fig.suptitle(
        "Supply Chain KPIs  ·  Delivery performance & profitability",
        fontsize=15, fontweight="bold", x=0.5, y=0.98,
    )

    # --- Panel 1: late-delivery rate by shipping mode ------------------------
    bars = ax1.bar(
        late_by_mode["shipping_mode"],
        late_by_mode["late_pct"],
        color=ACCENT, width=0.6,
    )
    ax1.set_title("Late-delivery rate by shipping mode", fontsize=12, fontweight="bold", pad=10)
    ax1.set_ylabel("% order lines shipped late")
    ax1.set_ylim(0, max(late_by_mode["late_pct"]) * 1.25)
    ax1.bar_label(bars, fmt="%.1f%%", padding=3, fontsize=10, color=INK)
    ax1.spines[["top", "right"]].set_visible(False)
    ax1.yaxis.grid(True, color=GRID, linewidth=0.8)
    ax1.set_axisbelow(True)
    ax1.tick_params(axis="x", labelrotation=15)

    # --- Panel 2: profit by region (positive vs negative) --------------------
    colors = [GOOD if v >= 0 else BAD for v in profit_by_region["total_profit"]]
    ax2.barh(profit_by_region["order_region"], profit_by_region["total_profit"], color=colors)
    ax2.set_title("Top 8 regions by total profit", fontsize=12, fontweight="bold", pad=10)
    ax2.set_xlabel("Total profit")
    ax2.axvline(0, color=INK, linewidth=0.8)
    ax2.spines[["top", "right"]].set_visible(False)
    ax2.xaxis.grid(True, color=GRID, linewidth=0.8)
    ax2.set_axisbelow(True)

    fig.text(
        0.5, 0.01,
        "Generated by supply-chain-etl  ·  github.com/sxntnx/supply-chain-etl-pipeline",
        ha="center", fontsize=8, color="#9ca3af",
    )

    fig.tight_layout(rect=(0, 0.03, 1, 0.95))
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out = REPORTS_DIR / "kpi_dashboard.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return out


def main() -> None:
    if not config.DATABASE_PATH.exists():
        raise FileNotFoundError(
            f"Database not found at '{config.DATABASE_PATH}'. "
            f"Run `python main.py` first."
        )
    with sqlite3.connect(config.DATABASE_PATH) as conn:
        late_by_mode, profit_by_region = load_frames(conn)
    out = render(late_by_mode, profit_by_region)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
